# Generated by Django 4.1.5 on 2023-01-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data',
            field=models.DateField(blank=True),
        ),
    ]
