# Generated by Django 4.1.5 on 2023-01-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='data',
        ),
    ]
