# Generated by Django 4.1.5 on 2023-02-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_bi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bi',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
