# Generated by Django 4.1.5 on 2023-02-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_bi'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='endereco1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='endereco2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
