# Generated by Django 4.1.5 on 2023-02-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='provincia',
            field=models.CharField(max_length=50),
        ),
    ]
