# Generated by Django 4.1.5 on 2023-02-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_conta',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_transferencia',
        ),
    ]
