# Generated by Django 4.1.5 on 2023-02-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_id_conta_remove_user_id_transferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saldo',
            field=models.IntegerField(default=0),
        ),
    ]
