# Generated by Django 4.1.5 on 2023-02-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idKipaga',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
