# Generated by Django 4.1.5 on 2023-02-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_idkipaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='saldo',
            field=models.FloatField(default=0),
        ),
    ]
