# Generated by Django 4.1.5 on 2023-03-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isempresa',
            field=models.BooleanField(default=False),
        ),
    ]
