# Generated by Django 4.1.5 on 2023-02-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='lido',
            field=models.BooleanField(default=False),
        ),
    ]
