# Generated by Django 4.1.5 on 2023-02-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_notify_lido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposito',
            name='valor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='valor',
            field=models.FloatField(),
        ),
    ]
