# Generated by Django 4.1.5 on 2023-04-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_bairro_empresa_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='Servico',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
